server:
  port: 8888
spring:
  cloud:
    config:
      name: SpringBootJwtAuthentication
      server:
        git:
          uri: https://github.com/manojchaulagain/config.git
          skip-ssl-validation: true
          username: manojchaulagain
          password: N1e2p3al!
  security:
    user:
      name: configserver
      password: mysecret